services:
  devcontainer:
    build: .
    image: devcontainer-shopper_challenge_api
    container_name: devcontainer-shopper_challenge_api
    command: ash -c "sleep infinity"
    ports:
      - 3000:3000
    working_dir: /home/node/rest-api
    volumes:
      - ../..:/home/node/rest-api
    env_file: ../../.env
    environment:
      NODE_ENV: development
      USER: node
      POSTGRES_HOST: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: shopper_challenge_development
    depends_on:
      - database

  database:
    image: postgres:alpine
    container_name: devcontainer-shopper_challenge_database
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: shopper_challenge_development
    mem_limit: 512m

  webdb:
    image: webdb/app
    container_name: devcontainer-shopper_challenge_webdb
    restart: always
    volumes:
      - webdb_data:/usr/src/app/static/version
    ports:
      - '22071:22071'

volumes:
  postgres_data:
    name: shopper_challenge_postgres_data
  webdb_data:
    name: shopper_challenge_webdb
